### ISSUE TITLE
Services Folder Empty

### ISSUE THREAD

**Issue by JoshuaKunz** [JoshuaKunz/PyDnD#32]
Within the character directory of the project I noticed that the services folder is empty. Lets just go ahead and remove that folder.

**Comment by Texdom65** [comment]
i dont seem to have a folder called "sevices" folder, so i dont know what you may be seeing...

**Comment by JoshuaKunz** [comment]
Oh ok I guess it must not be in there. In vscode I thought I saw it as character.database.services but if it's not in there than this issue can be closed.

**Comment by Texdom65** [comment]
ticket closed
