### ISSUE TITLE
Remove Old Branches

### ISSUE THREAD

**Issue by JoshuaKunz** [JoshuaKunz/PyDnD#34]
There are some branches that are not being used anymore, let's go ahead and remove them to keep our branches list clean.

**Comment by Texdom65** [comment]
do the old branches need to brought upto date before we get rid of them?

**Comment by JoshuaKunz** [comment]
No they can just be deleted as long as we know we don't need it anymore

**Comment by Texdom65** [comment]
deleted all the branches i know we have finished or no longer need.
