### ISSUE TITLE
THAC0

### ISSUE THREAD

**Issue by Texdom65** [JoshuaKunz/PyDnD#43]
create script and code to include THAC0 (To Hit Armor Class 0) to the character sheet.

**Comment by JoshuaKunz** [comment]
This can be achieved by adding thaco to the character.py character property like:
```python
self.thaco = 20
```

**Comment by Texdom65** [comment]
@JoshuaKunz 
theoretically, it would actually be like this
thac0 = 20
to_hit = 0
if char_dex == x:
    to_hit = thac0 (-/+) = y
etc...
